### ISSUE TITLE
请问作者这个项目的Flutter开发版本号是多少，我用Flutter2.5.3版本启动项目一直报错。感谢回复：）

### ISSUE THREAD

**Issue by lifan2000** [TreeLiked/walll#1]

**Comment by TreeLiked** [comment]
![image](https://user-images.githubusercontent.com/41715321/145157609-720dd351-800d-4619-b054-a03a338f1b4a.png)
报什么错？

**Comment by lifan2000** [comment]
谢谢作者回复，问题已经解决了。一开始报错如图，说是依赖内部方法错误。
<img width="1210" alt="052847351001E33D42784D0854047D20" src="https://user-images.githubusercontent.com/45134831/145171255-02b49688-3e44-4efe-b112-9e3581b2c9a7.png">
解决方式：pubspec.yaml中添加一行：decimal: 1.5.0，规定好版本。

也感谢作者愿意开源这么优秀的作品：）很适合拿来学习和修改
